print variables

diff --git a/.github/workflows/build-test-deploy.yaml b/.github/workflows/build-test-deploy.yaml
--- a/.github/workflows/build-test-deploy.yaml
+++ b/.github/workflows/build-test-deploy.yaml
@@ -169,10 +169,11 @@ jobs:
     needs: [ waiting_job, triage ]
     steps: 
       - run: |
-          echo !contains(needs.*.result, 'failure'): ${{ !contains(needs.*.result, 'failure') }}
-          echo !contains(needs.*.result, 'cancelled'): ${{ !contains(needs.*.result, 'cancelled') }}
-          echo needs.triage.outputs.RES != '1': ${{ needs.triage.outputs.RES != '1' }}
-          echo !needs.waiting_job.outputs.NOT_PROMOTED: ${{ !needs.waiting_job.outputs.NOT_PROMOTED }}
+          set -eux
+          echo 1: ${{ !contains(needs.*.result, 'failure') }}
+          echo 2: ${{ !contains(needs.*.result, 'cancelled') }}
+          echo 3: ${{ needs.triage.outputs.RES != '1' }}
+          echo 4: ${{ !needs.waiting_job.outputs.NOT_PROMOTED }}
 
   actual_job:
     if: |
